# fly.toml app configuration file generated for backend-kavi-sme
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "backend-kavi-sme"
primary_region = "iad"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory_mb = 256

[deploy]
  strategy = "immediate"


