# Generated by Django 5.2.6 on 2025-10-19 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('dba_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('year_founded', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('hq_country', models.CharField(blank=True, max_length=100)),
                ('hq_city', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('ownership_type', models.CharField(blank=True, max_length=100)),
                ('business_model', models.CharField(blank=True, max_length=50)),
                ('sales_motion', models.CharField(blank=True, max_length=50)),
                ('naics', models.CharField(blank=True, max_length=20)),
                ('sic', models.CharField(blank=True, max_length=20)),
                ('industry_keywords', models.TextField(blank=True)),
                ('revenue_band', models.CharField(blank=True, max_length=50)),
                ('funding_stage', models.CharField(blank=True, max_length=50)),
                ('regions', models.CharField(blank=True, max_length=255)),
                ('channels', models.CharField(blank=True, max_length=255)),
                ('regulated', models.BooleanField(default=False)),
                ('classified_category', models.CharField(blank=True, max_length=255)),
                ('classified_confidence', models.FloatField(blank=True, null=True)),
                ('classified_tags', models.JSONField(blank=True, null=True)),
                ('last_classified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
