# Generated by Django 5.2.6 on 2025-11-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('data_entry', 'Data Entry'), ('admin', 'Admin')], default='owner', max_length=20),
        ),
    ]
